apiVersion: v1
kind: Service
metadata:
  name: app1
  labels:
    app: app1
spec:
  selector:
    app: app1
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          # image: paulbouwer/hello-kubernetes:1.10
          image: ggjulio/app1:1.0
          # imagePullPolicy: Always
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 443
          #   initialDelaySeconds: 3
          #   periodSeconds: 3
          env:
            - name: MESSAGE
              value: Hello from app one
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
              name: http
